# data
dir_root: '../data/'
data_root: '../data/hf_round2_train'
arrythmia_path: '../data/hf_round2_arrythmia.txt'
train_txt_path: '../data/hf_round2_train.txt'
train_csv_path: '../user_data/hf_round2_label_testA.csv'
validation_csv_path: '../user_data/hf_round2_label_validation.csv'
test_root: '../data/testA'
test_label: '../data/hf_round1_subA.txt'
train_len: 16000
data_lens: 5000
num_classes: 34

# training
model: 'ResNeXt50_2x64d_Basic'
epochs: 48
batch_size: 32
num_workers: 8
model_save_path: '../user_data/checkpoints/ResNeXt50_2x64d_train_all_basic/'
loss: 'binary_crossentropy'
fast_train: True

# testing
load_model_path: '' #'../user_data/checkpoints/ResNeXt50_2x64d_train/ResNeXt50_2x64d_e40.ckpt'
flip: False

# optimizer
lr_mode : cosine
base_lr: 0.0003
warmup_epochs: 2
warmup_lr: 0.0
targetlr : 0.0
weight_decay: 0.00001
